TEXTS = {
    "ru": {
        "choose_language": "Выберите язык:",
        "language_saved": "Язык сохранён.",
        "main_menu_prompt": "Выберите действие:",
        "services": "💆 Услуги",
        "address": "📍 Адрес",
        "contact": "📞 Контакт",
        "choose_service": "Выберите услугу:",
        "service_with_price": "{name} ({price})",
        "choose_preferences": "Выберите предпочтение:",
        "choose_warnings": "Укажите предупреждения:",
        "custom_input": "Свой вариант",
        "skip": "Пропустить",
        "none": "Нет",
        "enter_preferences": "Напишите ваши предпочтения одним сообщением.",
        "enter_warnings": "Напишите предупреждение одним сообщением.",
        "choose_date": "Выберите дату:",
        "enter_manually": "Ввести вручную",
        "enter_date_manually": "Введите дату сообщением, например: 25.04.2026",
        "choose_time": "Выберите время:",
        "confirm": "Подтвердить",
        "edit": "Изменить",
        "summary_title": "Проверьте данные бронирования:",
        "summary_service": "Услуга: {value}",
        "summary_date": "Дата: {value}",
        "summary_time": "Время: {value}",
        "summary_preferences": "Предпочтения: {value}",
        "summary_warnings": "Предупреждения: {value}",
        "booking_created": "Заявка отправлена. Спасибо!",
        "booking_created_user": "Ваша запись подтверждена. Мы скоро свяжемся с вами.",
        "booking_created_test": "Это сообщение будет приходить вам, когда клиент будет отправлять заказ.",
        "booking_admin_title": "Новая заявка на бронирование",
        "booking_admin_username": "Username: {value}",
        "booking_admin_user_id": "User ID: {value}",
        "booking_restart": "Начнём заново. Выберите услугу:",
        "invalid_choice": "Пожалуйста, используйте кнопки ниже.",
        "invalid_date": "Не удалось распознать дату. Попробуйте ещё раз.",
        "date_unavailable": "Эта дата уже прошла. Пожалуйста, выберите другую дату.",
        "weekend_unavailable": "Доступны только будние дни. Пожалуйста, выберите дату с понедельника по пятницу.",
        "map_message": "Адрес:",
        "contact_message": "Связаться с мастером:",
        "missing_language": "Сначала выберите язык через /start.",
    },
    "en": {
        "choose_language": "Choose language:",
        "language_saved": "Language saved.",
        "main_menu_prompt": "Choose an action:",
        "services": "💆 Services",
        "address": "📍 Address",
        "contact": "📞 Contact",
        "choose_service": "Choose a service:",
        "service_with_price": "{name} ({price})",
        "choose_preferences": "Choose a preference:",
        "choose_warnings": "Add warnings:",
        "custom_input": "Custom input",
        "skip": "Skip",
        "none": "None",
        "enter_preferences": "Send your preferences in one message.",
        "enter_warnings": "Send your warning in one message.",
        "choose_date": "Choose a date:",
        "enter_manually": "Enter manually",
        "enter_date_manually": "Send the date in one message, for example: 25.04.2026",
        "choose_time": "Choose a time:",
        "confirm": "Confirm",
        "edit": "Edit",
        "summary_title": "Please confirm your booking:",
        "summary_service": "Service: {value}",
        "summary_date": "Date: {value}",
        "summary_time": "Time: {value}",
        "summary_preferences": "Preferences: {value}",
        "summary_warnings": "Warnings: {value}",
        "booking_created": "Booking request sent. Thank you!",
        "booking_created_user": "Your booking has been confirmed. We will contact you soon.",
        "booking_created_test": "This message will be sent to you when a client submits an order.",
        "booking_admin_title": "New booking request",
        "booking_admin_username": "Username: {value}",
        "booking_admin_user_id": "User ID: {value}",
        "booking_restart": "Let's start again. Choose a service:",
        "invalid_choice": "Please use the buttons below.",
        "invalid_date": "Date could not be recognized. Please try again.",
        "date_unavailable": "This date has already passed. Please choose another date.",
        "weekend_unavailable": "Only weekdays are available. Please choose a date from Monday to Friday.",
        "map_message": "Address:",
        "contact_message": "Contact the master:",
        "missing_language": "Please choose a language first with /start.",
    },
    "se": {
        "choose_language": "Välj språk:",
        "language_saved": "Språket har sparats.",
        "main_menu_prompt": "Välj ett alternativ:",
        "services": "💆 Tjänster",
        "address": "📍 Adress",
        "contact": "📞 Kontakt",
        "choose_service": "Välj en tjänst:",
        "service_with_price": "{name} ({price})",
        "choose_preferences": "Välj önskemål:",
        "choose_warnings": "Ange varningar:",
        "custom_input": "Eget svar",
        "skip": "Hoppa över",
        "none": "Ingen",
        "enter_preferences": "Skicka dina önskemål i ett meddelande.",
        "enter_warnings": "Skicka din varning i ett meddelande.",
        "choose_date": "Välj datum:",
        "enter_manually": "Skriv manuellt",
        "enter_date_manually": "Skicka datumet i ett meddelande, till exempel: 25.04.2026",
        "choose_time": "Välj tid:",
        "confirm": "Bekräfta",
        "edit": "Ändra",
        "summary_title": "Kontrollera din bokning:",
        "summary_service": "Tjänst: {value}",
        "summary_date": "Datum: {value}",
        "summary_time": "Tid: {value}",
        "summary_preferences": "Önskemål: {value}",
        "summary_warnings": "Varningar: {value}",
        "booking_created": "Bokningsförfrågan skickad. Tack!",
        "booking_created_user": "Din bokning är bekräftad. Vi kontaktar dig snart.",
        "booking_created_test": "Detta meddelande kommer att skickas till dig när en kund skickar en beställning.",
        "booking_admin_title": "Ny bokningsförfrågan",
        "booking_admin_username": "Användarnamn: {value}",
        "booking_admin_user_id": "Användar-ID: {value}",
        "booking_restart": "Vi börjar om. Välj en tjänst:",
        "invalid_choice": "Använd knapparna nedan.",
        "invalid_date": "Datumet kunde inte tolkas. Försök igen.",
        "date_unavailable": "Det datumet har redan passerat. Välj ett annat datum.",
        "weekend_unavailable": "Endast vardagar är tillgängliga. Välj ett datum från måndag till fredag.",
        "map_message": "Adress:",
        "contact_message": "Kontakta behandlaren:",
        "missing_language": "Välj först språk via /start.",
    },
}

LANGUAGE_LABELS = {
    "ru": "🇷🇺 Русский",
    "en": "🇬🇧 English",
    "se": "🇸🇪 Svenska",
}

LANGUAGE_BY_BUTTON = {value: key for key, value in LANGUAGE_LABELS.items()}
